version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - tmp_downloads:/app/downloads
    restart: always
    environment:
      - CLEANUP_INTERVAL=3600  # 1 hour in seconds

volumes:
  tmp_downloads:
    driver: local 