services:
  - type: web
    name: video-downloader
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn app:app --timeout 300 --workers 3
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1